Cliente* lerBaseDeDados();
void guardarBaseDeDados(Cliente* );
void libertarMemoria(Cliente* );
void adicionar(Cliente* );
Cliente* adicionarCliente(Cliente* , Cliente* );
int obterIdAleatorio(Cliente* );
bool existeCliente(Cliente* , int );
void editar(Cliente* );
void editarCliente(Cliente* , Cliente* );
Cliente* encontrarCliente(Cliente* , int );
void remover(Cliente* ) ;
Cliente* removerCliente(Cliente* , int );
void visualizarCliente(Cliente* );
